name: my_friend
version: 0.0.1+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  firebase_analytics: ^9.2.0
  sentry_flutter: ^6.6.3
  flutter_phoenix: ^1.0.0
  get: ^4.6.5
  dio: ^4.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: launcher_icon
  image_path: assets/icon/icon.png
  ios: true

flutter:
  uses-material-design: true
